openapi: 3.0.0

info:
  version: 1.0.0
  title: auth-api-ktor∏
  description: auth-api-ktorのAPIドキュメントです。

servers:
  - url: "http://localhost:3000"
    description: "本番環境"

tags:
  - name: "auth"
    description: 認証用API
  - name: "users"
    description: ユーザ情報取得用API

paths:
  /auth/login:
    $ref: paths/login.yaml
  /auth/register:
    $ref: paths/register.yaml